# Generated by Django 3.2.16 on 2023-01-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('Actor', models.CharField(max_length=241)),
                ('Actress', models.CharField(max_length=251)),
            ],
        ),
    ]
