# Generated by Django 3.2.16 on 2023-01-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Actor',
            new_name='Stars',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Actress',
        ),
    ]
