# Generated by Django 3.2.16 on 2023-01-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_auto_20230109_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='asdf', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
